# +============================================================================+
# | Company:   SOFiSTiK AG                                                     |
# | Version:   SOFiSTiK 2026                                                   |
# +============================================================================+

# This example has been tested with Python 3.12.2 (64-bit)

################################### IMPORT ####################################

# Import all types from "sofistik_daten.py" (automatically generated by SOFiSTiK)
from sofistik_daten import *

# Load DLL
import os

# Provides C compatible data types, and allows calling functions in DLLs
from ctypes import *

################################### SOURCE ####################################

# See for more information: https://docs.python.org/3/whatsnew/3.8.html#ctypes
os.add_dll_directory(r"C:\Program Files\SOFiSTiK\2026\SOFiSTiK 2026\interfaces\64bit")
os.add_dll_directory(r"C:\Program Files\SOFiSTiK\2026\SOFiSTiK 2026")

cdb_dll = cdll.LoadLibrary("sof_cdb_w-2026.dll")

# Connect to CDB
cdb_index = c_int()

# Set the CDB Path
filename = r"single_span_girder.cdb"

# Important: Unicode call!
cdb_index.value = cdb_dll.sof_cdb_init(filename.encode("utf8"), 99)

cdb_stat = c_int()  # get the CDB status
cdb_stat.value = cdb_dll.sof_cdb_status(cdb_index.value)

# Print the Status of the CDB
print("CDB Status:", cdb_stat.value)

# Print again the status of the CDB, if status = 0 -> CDB Closed successfully
cdb_stat.value = cdb_dll.sof_cdb_status(cdb_index.value)
if cdb_stat.value == 0:
    print("CDB closed successfully, status = 0")
