"""
Column Design Wizard — SOFiSTiK COLUMN module integration.

Generates a standalone single-column .dat, runs SPS, parses .erg output.
Works for any model type (SOFIMSHA or SOFIMSHC) by reading forces from
the existing SQLite and building a fresh minimal CDB.
"""

import os
import re
import sqlite3
import subprocess
import tempfile
import math
from pathlib import Path

SOFISTIK_DIR = r"C:\Program Files\SOFiSTiK\2026\SOFiSTiK 2026"
SPS_EXE = os.path.join(SOFISTIK_DIR, "sps.exe")

CONCRETE_GRADES = ["C20", "C25", "C30", "C35", "C40", "C45", "C50"]
STEEL_GRADES = ["B500A", "B500B", "B500C"]

# fck values in MPa
FCK = {"C20": 20, "C25": 25, "C30": 30, "C35": 35,
       "C40": 40, "C45": 45, "C50": 50}
FYK = 500  # all B500x grades


# ── .dat Generator ───────────────────────────────────────────────────────────

def generate_column_dat(
    section_b: float,   # width  [m]
    section_h: float,   # height [m]
    col_length: float,  # buckling length [m]
    N_kN: float,        # axial force [kN], positive = tension
    My_kNm: float,      # bending moment about y [kNm]
    Mz_kNm: float,      # bending moment about z [kNm]
    concrete: str = "C30",
    steel: str = "B500B",
    cover_y: int = 50,  # cover parallel to y-axis [mm]
    cover_z: int = 50,  # cover parallel to z-axis [mm]
    beta_y: float = 1.0,
    beta_z: float = 1.0,
) -> str:
    """Generate a minimal standalone COLUMN check .dat."""

    # SOFiSTiK concrete name: C30 → c '30'
    conc_token = f"c '{concrete[1:]}'"
    steel_token = f"b '{steel[1:].lower()}'"

    # SOFILOAD force sign convention:
    #   PZZ positive = downward = compression for vertical column
    #   N positive = tension in infrafem → flip sign for PZZ
    pzz = -N_kN
    myy = My_kNm
    mxx = Mz_kNm

    lines = [
        "$ Generated by infraFEM Column Wizard",
        "$",
        "+prog aqua urs:1",
        "head Cross-Section",
        "page unii 0",
        "norm din en199x-200x coun 49",
        f"conc 1 {conc_token}",
        f"stee 2 {steel_token}",
        (f"srec 1 h {section_h*1000:.0f}[mm] b {section_b*1000:.0f}[mm] "
         f"so {cover_z:.0f} su {cover_z:.0f} ss {cover_y:.0f} "
         f"mno 1 mrf 2 rtyp cu"),
        "end",
        "",
        "+prog sofimshc urs:2",
        "head Column Geometry",
        "page unii 0",
        "echo full 0",
        "syst 3d gdiv 10000 gdir posz",
        "ctrl mesh 1",
        f"ctrl hmin {min(col_length / 4.0, 0.5):.2f}",
        "ctrl tolg 0.02",
        "",
        "spt 1 x 0 0 0       fix ppmm  $ base: fully fixed",
        f"spt 2 x 0 0 {-col_length:.3f}         $ top: free",
        "",
        "sln 1 npa 1 2 sno 1 titl column",
        "end",
        "",
        "+prog sofiload urs:3",
        "head Design Forces",
        "page unii 0",
        "echo full 0",
        "lc 1001 type (D) titl ULS_Ed",
    ]

    if abs(pzz) > 0.01:
        lines.append(f" poin ref node 2 type pzz {pzz:.3f}")
    if abs(myy) > 0.01:
        lines.append(f" poin ref node 2 type myy {myy:.3f}")
    if abs(mxx) > 0.01:
        lines.append(f" poin ref node 2 type mxx {mxx:.3f}")

    lines += [
        "end",
        "",
        "+prog ase urs:4",
        "head Analysis",
        "echo full no",
        "lc 1001",
        "end",
        "",
        "+prog column urs:5",
        "head Column Design",
        "page unii 0 lano 0",
        "echo mat",
        "echo sect",
        "echo syst",
        "echo comb full",
        "echo forc full",
        "echo rein full",
        "ctrl nett yes",
        "ctrl ncm",
        "",
        "dgrp no DG01 titl infrafem_column",
        f"geom bety {beta_y:.2f} betz {beta_z:.2f} cy {cover_z:.0f} cz {cover_z:.0f}",
        "",
        "comb lc 1001 type (D) titl ULS",
        " copy no 1001 fact 1.0",
        "",
        "sln 1 axis col lev L0",
        "end",
    ]
    return "\n".join(lines)


# ── SPS Runner ────────────────────────────────────────────────────────────────

def run_column_check(dat_text: str) -> dict:
    """
    Write .dat to temp dir, run SPS, parse .erg output.
    Returns dict: {success, eta, as_req_cm2, as_min_cm2, rho_pct,
                   n_design, my_design, raw_erg, error}
    """
    if not os.path.exists(SPS_EXE):
        return {"success": False, "error": f"SPS not found: {SPS_EXE}"}

    work_dir = tempfile.mkdtemp(prefix="col_wiz_")
    dat_path = os.path.join(work_dir, "col_check.dat")
    erg_path = os.path.join(work_dir, "col_check.erg")

    with open(dat_path, "w", encoding="utf-8") as f:
        f.write(dat_text)

    try:
        result = subprocess.run(
            [SPS_EXE, "-B", dat_path],
            capture_output=True,
            cwd=work_dir,
            timeout=60,
        )
        log = (result.stdout or b"").decode("latin-1", errors="replace")
        log += (result.stderr or b"").decode("latin-1", errors="replace")

        if not os.path.exists(erg_path) or os.path.getsize(erg_path) < 50:
            return {
                "success": False,
                "error": "SPS did not produce .erg output",
                "sps_log": log[:2000],
            }

        with open(erg_path, "r", encoding="latin-1", errors="replace") as f:
            erg_text = f.read()

        parsed = parse_column_erg(erg_text)
        parsed["success"] = True
        parsed["raw_erg"] = erg_text
        return parsed

    except subprocess.TimeoutExpired:
        return {"success": False, "error": "SPS timed out (>60s)"}
    except Exception as e:
        return {"success": False, "error": str(e)}
    finally:
        # Clean up temp files (keep for debugging if failed)
        pass


# ── .erg Parser ───────────────────────────────────────────────────────────────

def parse_column_erg(erg_text: str) -> dict:
    """
    Extract design results from COLUMN .erg text output.
    Handles both English (LANO 0) and German output variants.
    """
    result = {
        "eta": None,
        "as_req_cm2": None,
        "as_min_cm2": None,
        "rho_pct": None,
        "n_design_kN": None,
        "my_design_kNm": None,
        "status": "unknown",
    }

    # Utilization ratio: "eta = 0.73" or "Ausnutzung  0.73" or "ETA    0.73"
    for pat in [
        r"[Ee][Tt][Aa]\s*[=:]\s*([\d.]+)",
        r"[Ee][Tt][Aa]\s+([\d.]+)",
        r"Ausnutzung\s+([\d.]+)",
        r"utilisation\s+([\d.]+)",
        r"utilization\s+([\d.]+)",
    ]:
        m = re.search(pat, erg_text, re.IGNORECASE)
        if m:
            try:
                result["eta"] = float(m.group(1))
                break
            except ValueError:
                pass

    # Required reinforcement: "As,req = 12.56 cm2" or "AS,REQ   12.56"
    for pat in [
        r"[Aa][Ss][,.]?[Rr][Ee][Qq][^0-9]*([\d.]+)\s*cm",
        r"[Aa][Ss][,.]?[Ee][Rr][Ff][^0-9]*([\d.]+)\s*cm",
        r"REINF.*?REQUIRED[^0-9]*([\d.]+)",
        r"As\s*,\s*req\s*=\s*([\d.]+)",
        r"erforderliche.*?Bewehrung[^0-9]*([\d.]+)",
    ]:
        m = re.search(pat, erg_text, re.IGNORECASE)
        if m:
            try:
                result["as_req_cm2"] = float(m.group(1))
                break
            except ValueError:
                pass

    # Minimum reinforcement
    for pat in [
        r"[Aa][Ss][,.]?[Mm][Ii][Nn][^0-9]*([\d.]+)\s*cm",
        r"As\s*,\s*min\s*=\s*([\d.]+)",
        r"Mindestbewehrung[^0-9]*([\d.]+)",
    ]:
        m = re.search(pat, erg_text, re.IGNORECASE)
        if m:
            try:
                result["as_min_cm2"] = float(m.group(1))
                break
            except ValueError:
                pass

    # Reinforcement ratio rho [%]
    for pat in [
        r"[Rr]ho\s*[=:]\s*([\d.]+)\s*%",
        r"[Rr]einf.*?ratio[^0-9]*([\d.]+)\s*%",
    ]:
        m = re.search(pat, erg_text, re.IGNORECASE)
        if m:
            try:
                result["rho_pct"] = float(m.group(1))
                break
            except ValueError:
                pass

    # Design forces from output
    m = re.search(r"N\s*Ed[^0-9-]*([-\d.]+)", erg_text, re.IGNORECASE)
    if m:
        try:
            result["n_design_kN"] = float(m.group(1))
        except ValueError:
            pass

    m = re.search(r"M\s*y[^0-9-]*([-\d.]+)", erg_text, re.IGNORECASE)
    if m:
        try:
            result["my_design_kNm"] = float(m.group(1))
        except ValueError:
            pass

    # Status
    if result["eta"] is not None:
        if result["eta"] <= 1.0:
            result["status"] = "OK"
        else:
            result["status"] = "FAIL"
    elif re.search(r"ERROR|FEHLER|failed", erg_text, re.IGNORECASE):
        result["status"] = "error"

    return result


# ── Interaction Diagram (Python-computed, EN 1992 simplified) ─────────────────

def compute_interaction_diagram(
    b: float,       # width [m]
    h: float,       # height [m]
    fck: float,     # concrete char. strength [MPa]
    fyk: float,     # steel char. strength [MPa]
    cover: float,   # cover [mm]
    n_points: int = 40,
) -> list[dict]:
    """
    Simplified N-M interaction diagram for rectangular RC section.
    Concrete: parabolic-rectangular (EN 1992). Steel: bi-linear.
    Returns list of {N_kN, M_kNm} capacity points.
    """
    # Design strengths
    fcd = fck / 1.5     # MPa
    fyd = fyk / 1.15    # MPa
    Es = 200_000        # MPa
    eps_cu = 0.0035     # concrete ultimate strain
    eps_yd = fyd / Es   # steel yield strain

    # Geometry in mm
    b_mm = b * 1000
    h_mm = h * 1000
    d = h_mm - cover - 10   # effective depth (approx. bar radius 10mm)
    d2 = cover + 10          # compression cover

    # Assumed symmetric reinforcement: As1 = As2 = As/2
    # We parameterise over neutral axis depth x/h from 0 → ∞
    # plus tension/compression dominated zones.

    points = []

    def section_forces(x_mm: float, As_mm2: float):
        """N [kN], M [kNm] for given NA depth x and total reinforcement."""
        # Concrete compression block (simplified rectangular α=0.8, η=1.0 for C≤50)
        alpha = 0.8
        lam = 0.8
        x_lim = min(x_mm, h_mm)
        xc = lam * x_lim  # height of rectangular stress block
        Nc = alpha * fcd * b_mm * xc / 1000   # kN (force in compression block)

        # Strain at steel levels
        if x_mm > 0:
            eps_s1 = eps_cu * (x_mm - d2) / x_mm   # top steel (compression side)
            eps_s2 = eps_cu * (x_mm - d) / x_mm    # bottom steel
        else:
            eps_s1 = -eps_yd
            eps_s2 = -eps_yd

        # Steel stresses (capped at fyd)
        sig_s1 = max(-fyd, min(fyd, Es * eps_s1))
        sig_s2 = max(-fyd, min(fyd, Es * eps_s2))

        As1 = As2 = As_mm2 / 2
        Ns1 = sig_s1 * As1 / 1000   # kN
        Ns2 = sig_s2 * As2 / 1000   # kN

        N_kN = Nc + Ns1 + Ns2
        # Moments about section centroid (h/2)
        yc = h_mm / 2 - xc / 2        # distance of concrete block centroid from mid
        ys1 = h_mm / 2 - d2           # top steel distance from mid (compression)
        ys2 = d - h_mm / 2            # bottom steel distance from mid (tension)

        M_kNm = (Nc * yc + Ns1 * ys1 - Ns2 * ys2) / 1_000  # kNm
        return N_kN, abs(M_kNm)

    # Minimum reinforcement ratio: As,min = max(0.1*|N_Ed|/fyd, 0.002*Ac)
    Ac_mm2 = b_mm * h_mm
    As_min = max(0.002 * Ac_mm2, 0.1 * fcd * Ac_mm2 / fyd)
    As_used = As_min  # use minimum for the diagram

    # Sweep neutral axis x from -h (pure tension) to 5h (deep compression)
    x_values = []
    # Tension zone: x from -h to 0 (interpolate strain)
    for i in range(8):
        x_values.append(-h_mm + i * h_mm / 8)
    # Compression zone: x from 0 to 5h
    for i in range(n_points - 8):
        x_values.append(i * 5 * h_mm / (n_points - 8))

    for x in x_values:
        try:
            N, M = section_forces(x, As_used)
            if abs(N) < 1e6 and abs(M) < 1e6:
                points.append({"N_kN": round(N, 1), "M_kNm": round(M, 1)})
        except Exception:
            pass

    # Add pure compression and pure tension boundary points
    N_pure_comp = (fcd * b_mm * h_mm + fyd * As_used) / 1000
    N_pure_ten = -fyd * As_used / 1000
    points.insert(0, {"N_kN": round(N_pure_ten, 1), "M_kNm": 0.0})
    points.append({"N_kN": round(N_pure_comp, 1), "M_kNm": 0.0})

    return points


# ── SQLite helpers ────────────────────────────────────────────────────────────

def get_beam_info(db_path: str, elem_nr: int) -> dict | None:
    """Get cross-section dimensions and length for a beam element."""
    conn = sqlite3.connect(db_path)
    conn.row_factory = sqlite3.Row
    try:
        row = conn.execute("""
            SELECT fl.length, fl.cross_section_at_start AS sec_nr,
                   cs.data, cs.name
            FROM fe_line fl
            JOIN cross_section cs ON cs.number = fl.cross_section_at_start
            WHERE fl.number = ?
        """, (elem_nr,)).fetchone()
        if not row:
            return None

        # Parse bounding box from blob
        import struct
        data = row["data"]
        pts = []
        i = 12
        while i < len(data) - 19:
            if data[i] == 0x00 and data[i + 1] == 0x08:
                y = struct.unpack("<d", data[i + 2:i + 10])[0]
                if data[i + 10] == 0x28:
                    z = struct.unpack("<d", data[i + 11:i + 19])[0]
                    post = data[i + 19] if i + 19 < len(data) else 0
                    if abs(y) < 50 and abs(z) < 50 and post == 0x01:
                        pts.append((y, z))
                        i += 20
                        continue
            i += 1

        if pts:
            ys = [p[0] for p in pts]
            zs = [p[1] for p in pts]
            b = max(ys) - min(ys)   # width in m
            h = max(zs) - min(zs)   # height in m
        else:
            b = h = 0.3  # fallback

        return {
            "length": row["length"],
            "section_name": row["name"] or f"sec {row['sec_nr']}",
            "b": b,
            "h": h,
        }
    finally:
        conn.close()


def get_beam_forces(db_path: str, elem_nr: int, lc: int) -> dict | None:
    """Get worst-case forces (max |N|) for an element in a load case."""
    conn = sqlite3.connect(db_path)
    conn.row_factory = sqlite3.Row
    try:
        # Detect schema variant
        cols = {r[1] for r in conn.execute(
            "PRAGMA table_info(fe_result_beam_internal_force)"
        ).fetchall()}
        lc_col = "load_case_id" if "load_case_id" in cols else "load_case_no"
        elem_col = "element_id" if "element_id" in cols else "beam_no"

        rows = conn.execute(f"""
            SELECT N, Vy, Vz, Mt, My, Mz
            FROM fe_result_beam_internal_force
            WHERE [{lc_col}] = ? AND [{elem_col}] = ?
            ORDER BY ABS(N) DESC
        """, (lc, elem_nr)).fetchall()

        if not rows:
            return None

        # Use the row with maximum |N| (worst compression or tension)
        r = rows[0]
        return {
            "N": r["N"],
            "Vy": r["Vy"],
            "Vz": r["Vz"],
            "My": r["My"],
            "Mz": r["Mz"],
        }
    finally:
        conn.close()
